/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class CategoryLanguage.
* @enum {}
* @readonly
*/
export default class CategoryLanguage {
    
        /**
         * value: "DEFAULT"
         * @const
         */
        "DEFAULT" = "DEFAULT";

    
        /**
         * value: "RU"
         * @const
         */
        "RU" = "RU";

    
        /**
         * value: "EN"
         * @const
         */
        "EN" = "EN";

    
        /**
         * value: "TR"
         * @const
         */
        "TR" = "TR";

    

    /**
    * Returns a <code>CategoryLanguage</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/CategoryLanguage} The enum <code>CategoryLanguage</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

