/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Fbsv3PostingProductDetailWithoutDimensions from './Fbsv3PostingProductDetailWithoutDimensions';

/**
 * The FbsPostingShipV3ResponseShipAdditionalData model module.
 * @module model/FbsPostingShipV3ResponseShipAdditionalData
 * @version 2.1
 */
class FbsPostingShipV3ResponseShipAdditionalData {
    /**
     * Constructs a new <code>FbsPostingShipV3ResponseShipAdditionalData</code>.
     * @alias module:model/FbsPostingShipV3ResponseShipAdditionalData
     */
    constructor() { 
        
        FbsPostingShipV3ResponseShipAdditionalData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FbsPostingShipV3ResponseShipAdditionalData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FbsPostingShipV3ResponseShipAdditionalData} obj Optional instance to populate.
     * @return {module:model/FbsPostingShipV3ResponseShipAdditionalData} The populated <code>FbsPostingShipV3ResponseShipAdditionalData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FbsPostingShipV3ResponseShipAdditionalData();

            if (data.hasOwnProperty('posting_number')) {
                obj['posting_number'] = ApiClient.convertToType(data['posting_number'], 'String');
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = ApiClient.convertToType(data['products'], [Fbsv3PostingProductDetailWithoutDimensions]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FbsPostingShipV3ResponseShipAdditionalData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FbsPostingShipV3ResponseShipAdditionalData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['posting_number'] && !(typeof data['posting_number'] === 'string' || data['posting_number'] instanceof String)) {
            throw new Error("Expected the field `posting_number` to be a primitive type in the JSON string but got " + data['posting_number']);
        }
        if (data['products']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['products'])) {
                throw new Error("Expected the field `products` to be an array in the JSON data but got " + data['products']);
            }
            // validate the optional field `products` (array)
            for (const item of data['products']) {
                Fbsv3PostingProductDetailWithoutDimensions.validateJsonObject(item);
            };
        }

        return true;
    }


}



/**
 * Номер отправления.
 * @member {String} posting_number
 */
FbsPostingShipV3ResponseShipAdditionalData.prototype['posting_number'] = undefined;

/**
 * Список товаров в отправлении.
 * @member {Array.<module:model/Fbsv3PostingProductDetailWithoutDimensions>} products
 */
FbsPostingShipV3ResponseShipAdditionalData.prototype['products'] = undefined;






export default FbsPostingShipV3ResponseShipAdditionalData;

