/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FbsPostingShipV4RequestWith model module.
 * @module model/FbsPostingShipV4RequestWith
 * @version 2.1
 */
class FbsPostingShipV4RequestWith {
    /**
     * Constructs a new <code>FbsPostingShipV4RequestWith</code>.
     * Дополнительная информация.
     * @alias module:model/FbsPostingShipV4RequestWith
     */
    constructor() { 
        
        FbsPostingShipV4RequestWith.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FbsPostingShipV4RequestWith</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FbsPostingShipV4RequestWith} obj Optional instance to populate.
     * @return {module:model/FbsPostingShipV4RequestWith} The populated <code>FbsPostingShipV4RequestWith</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FbsPostingShipV4RequestWith();

            if (data.hasOwnProperty('additional_data')) {
                obj['additional_data'] = ApiClient.convertToType(data['additional_data'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FbsPostingShipV4RequestWith</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FbsPostingShipV4RequestWith</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Чтобы получить дополнительную информацию, передайте `true`.
 * @member {Boolean} additional_data
 */
FbsPostingShipV4RequestWith.prototype['additional_data'] = undefined;






export default FbsPostingShipV4RequestWith;

