/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FbsPostingDetailCourier model module.
 * @module model/FbsPostingDetailCourier
 * @version 2.1
 */
class FbsPostingDetailCourier {
    /**
     * Constructs a new <code>FbsPostingDetailCourier</code>.
     * Данные о курьере.
     * @alias module:model/FbsPostingDetailCourier
     */
    constructor() { 
        
        FbsPostingDetailCourier.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FbsPostingDetailCourier</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FbsPostingDetailCourier} obj Optional instance to populate.
     * @return {module:model/FbsPostingDetailCourier} The populated <code>FbsPostingDetailCourier</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FbsPostingDetailCourier();

            if (data.hasOwnProperty('car_model')) {
                obj['car_model'] = ApiClient.convertToType(data['car_model'], 'String');
            }
            if (data.hasOwnProperty('car_number')) {
                obj['car_number'] = ApiClient.convertToType(data['car_number'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FbsPostingDetailCourier</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FbsPostingDetailCourier</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['car_model'] && !(typeof data['car_model'] === 'string' || data['car_model'] instanceof String)) {
            throw new Error("Expected the field `car_model` to be a primitive type in the JSON string but got " + data['car_model']);
        }
        // ensure the json data is a string
        if (data['car_number'] && !(typeof data['car_number'] === 'string' || data['car_number'] instanceof String)) {
            throw new Error("Expected the field `car_number` to be a primitive type in the JSON string but got " + data['car_number']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }

        return true;
    }


}



/**
 * Модель автомобиля.
 * @member {String} car_model
 */
FbsPostingDetailCourier.prototype['car_model'] = undefined;

/**
 * Номер автомобиля.
 * @member {String} car_number
 */
FbsPostingDetailCourier.prototype['car_number'] = undefined;

/**
 * Полное имя курьера.
 * @member {String} name
 */
FbsPostingDetailCourier.prototype['name'] = undefined;

/**
 * Телефон курьера.
 * @member {String} phone
 */
FbsPostingDetailCourier.prototype['phone'] = undefined;






export default FbsPostingDetailCourier;

