/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Fbsv4GetProductExemplarStatusResponseProduct from './Fbsv4GetProductExemplarStatusResponseProduct';

/**
 * The Fbsv4GetProductExemplarStatusResponse model module.
 * @module model/Fbsv4GetProductExemplarStatusResponse
 * @version 2.1
 */
class Fbsv4GetProductExemplarStatusResponse {
    /**
     * Constructs a new <code>Fbsv4GetProductExemplarStatusResponse</code>.
     * @alias module:model/Fbsv4GetProductExemplarStatusResponse
     */
    constructor() { 
        
        Fbsv4GetProductExemplarStatusResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Fbsv4GetProductExemplarStatusResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Fbsv4GetProductExemplarStatusResponse} obj Optional instance to populate.
     * @return {module:model/Fbsv4GetProductExemplarStatusResponse} The populated <code>Fbsv4GetProductExemplarStatusResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Fbsv4GetProductExemplarStatusResponse();

            if (data.hasOwnProperty('posting_number')) {
                obj['posting_number'] = ApiClient.convertToType(data['posting_number'], 'String');
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = ApiClient.convertToType(data['products'], [Fbsv4GetProductExemplarStatusResponseProduct]);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Fbsv4GetProductExemplarStatusResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Fbsv4GetProductExemplarStatusResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['posting_number'] && !(typeof data['posting_number'] === 'string' || data['posting_number'] instanceof String)) {
            throw new Error("Expected the field `posting_number` to be a primitive type in the JSON string but got " + data['posting_number']);
        }
        if (data['products']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['products'])) {
                throw new Error("Expected the field `products` to be an array in the JSON data but got " + data['products']);
            }
            // validate the optional field `products` (array)
            for (const item of data['products']) {
                Fbsv4GetProductExemplarStatusResponseProduct.validateJsonObject(item);
            };
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * Номер отправления.
 * @member {String} posting_number
 */
Fbsv4GetProductExemplarStatusResponse.prototype['posting_number'] = undefined;

/**
 * Список товаров.
 * @member {Array.<module:model/Fbsv4GetProductExemplarStatusResponseProduct>} products
 */
Fbsv4GetProductExemplarStatusResponse.prototype['products'] = undefined;

/**
 * Статус проверки всех экземпляров и доступности сборки: - `ship_available` — сборка доступна, - `ship_not_available` — сборка недоступна, - `validation_in_process` — экземпляры на проверке. 
 * @member {String} status
 */
Fbsv4GetProductExemplarStatusResponse.prototype['status'] = undefined;






export default Fbsv4GetProductExemplarStatusResponse;

