/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Fbsv4GetProductExemplarStatusRequest model module.
 * @module model/Fbsv4GetProductExemplarStatusRequest
 * @version 2.1
 */
class Fbsv4GetProductExemplarStatusRequest {
    /**
     * Constructs a new <code>Fbsv4GetProductExemplarStatusRequest</code>.
     * @alias module:model/Fbsv4GetProductExemplarStatusRequest
     */
    constructor() { 
        
        Fbsv4GetProductExemplarStatusRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Fbsv4GetProductExemplarStatusRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Fbsv4GetProductExemplarStatusRequest} obj Optional instance to populate.
     * @return {module:model/Fbsv4GetProductExemplarStatusRequest} The populated <code>Fbsv4GetProductExemplarStatusRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Fbsv4GetProductExemplarStatusRequest();

            if (data.hasOwnProperty('posting_number')) {
                obj['posting_number'] = ApiClient.convertToType(data['posting_number'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Fbsv4GetProductExemplarStatusRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Fbsv4GetProductExemplarStatusRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['posting_number'] && !(typeof data['posting_number'] === 'string' || data['posting_number'] instanceof String)) {
            throw new Error("Expected the field `posting_number` to be a primitive type in the JSON string but got " + data['posting_number']);
        }

        return true;
    }


}



/**
 * Номер отправления.
 * @member {String} posting_number
 */
Fbsv4GetProductExemplarStatusRequest.prototype['posting_number'] = undefined;






export default Fbsv4GetProductExemplarStatusRequest;

