/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FinanceTransactionTotalsV3RequestDate model module.
 * @module model/FinanceTransactionTotalsV3RequestDate
 * @version 2.1
 */
class FinanceTransactionTotalsV3RequestDate {
    /**
     * Constructs a new <code>FinanceTransactionTotalsV3RequestDate</code>.
     * Фильтр по дате.
     * @alias module:model/FinanceTransactionTotalsV3RequestDate
     */
    constructor() { 
        
        FinanceTransactionTotalsV3RequestDate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FinanceTransactionTotalsV3RequestDate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FinanceTransactionTotalsV3RequestDate} obj Optional instance to populate.
     * @return {module:model/FinanceTransactionTotalsV3RequestDate} The populated <code>FinanceTransactionTotalsV3RequestDate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FinanceTransactionTotalsV3RequestDate();

            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'Date');
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FinanceTransactionTotalsV3RequestDate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FinanceTransactionTotalsV3RequestDate</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Начало периода.  Формат: YYYY-MM-DDTHH:mm:ss.sssZ.<br> Пример: 2019-11-25T10:43:06.51. 
 * @member {Date} from
 */
FinanceTransactionTotalsV3RequestDate.prototype['from'] = undefined;

/**
 * Конец периода.  Формат: YYYY-MM-DDTHH:mm:ss.sssZ.<br> Пример: 2019-11-25T10:43:06.51. 
 * @member {Date} to
 */
FinanceTransactionTotalsV3RequestDate.prototype['to'] = undefined;






export default FinanceTransactionTotalsV3RequestDate;

