/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostingProductChangeRequestItem model module.
 * @module model/PostingProductChangeRequestItem
 * @version 2.1
 */
class PostingProductChangeRequestItem {
    /**
     * Constructs a new <code>PostingProductChangeRequestItem</code>.
     * @alias module:model/PostingProductChangeRequestItem
     */
    constructor() { 
        
        PostingProductChangeRequestItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostingProductChangeRequestItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostingProductChangeRequestItem} obj Optional instance to populate.
     * @return {module:model/PostingProductChangeRequestItem} The populated <code>PostingProductChangeRequestItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostingProductChangeRequestItem();

            if (data.hasOwnProperty('sku')) {
                obj['sku'] = ApiClient.convertToType(data['sku'], 'Number');
            }
            if (data.hasOwnProperty('weightReal')) {
                obj['weightReal'] = ApiClient.convertToType(data['weightReal'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostingProductChangeRequestItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostingProductChangeRequestItem</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['weightReal'])) {
            throw new Error("Expected the field `weightReal` to be an array in the JSON data but got " + data['weightReal']);
        }

        return true;
    }


}



/**
 * Идентификатор товара в системе Ozon — SKU.
 * @member {Number} sku
 */
PostingProductChangeRequestItem.prototype['sku'] = undefined;

/**
 * Вес единиц товара в отправлении.
 * @member {Array.<Number>} weightReal
 */
PostingProductChangeRequestItem.prototype['weightReal'] = undefined;






export default PostingProductChangeRequestItem;

