/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostingProductCancelRequestItem model module.
 * @module model/PostingProductCancelRequestItem
 * @version 2.1
 */
class PostingProductCancelRequestItem {
    /**
     * Constructs a new <code>PostingProductCancelRequestItem</code>.
     * @alias module:model/PostingProductCancelRequestItem
     */
    constructor() { 
        
        PostingProductCancelRequestItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostingProductCancelRequestItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostingProductCancelRequestItem} obj Optional instance to populate.
     * @return {module:model/PostingProductCancelRequestItem} The populated <code>PostingProductCancelRequestItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostingProductCancelRequestItem();

            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('sku')) {
                obj['sku'] = ApiClient.convertToType(data['sku'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostingProductCancelRequestItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostingProductCancelRequestItem</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Количество товара в отправлении.
 * @member {Number} quantity
 */
PostingProductCancelRequestItem.prototype['quantity'] = undefined;

/**
 * Идентификатор товара в системе Ozon — SKU.
 * @member {Number} sku
 */
PostingProductCancelRequestItem.prototype['sku'] = undefined;






export default PostingProductCancelRequestItem;

