/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FbsPostingTrackingNumberSetRequestTrackingNumber from './FbsPostingTrackingNumberSetRequestTrackingNumber';

/**
 * The PostingFbsPostingTrackingNumberSetRequest model module.
 * @module model/PostingFbsPostingTrackingNumberSetRequest
 * @version 2.1
 */
class PostingFbsPostingTrackingNumberSetRequest {
    /**
     * Constructs a new <code>PostingFbsPostingTrackingNumberSetRequest</code>.
     * @alias module:model/PostingFbsPostingTrackingNumberSetRequest
     */
    constructor() { 
        
        PostingFbsPostingTrackingNumberSetRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostingFbsPostingTrackingNumberSetRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostingFbsPostingTrackingNumberSetRequest} obj Optional instance to populate.
     * @return {module:model/PostingFbsPostingTrackingNumberSetRequest} The populated <code>PostingFbsPostingTrackingNumberSetRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostingFbsPostingTrackingNumberSetRequest();

            if (data.hasOwnProperty('tracking_numbers')) {
                obj['tracking_numbers'] = ApiClient.convertToType(data['tracking_numbers'], [FbsPostingTrackingNumberSetRequestTrackingNumber]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostingFbsPostingTrackingNumberSetRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostingFbsPostingTrackingNumberSetRequest</code>.
     */
    static validateJSON(data) {
        if (data['tracking_numbers']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['tracking_numbers'])) {
                throw new Error("Expected the field `tracking_numbers` to be an array in the JSON data but got " + data['tracking_numbers']);
            }
            // validate the optional field `tracking_numbers` (array)
            for (const item of data['tracking_numbers']) {
                FbsPostingTrackingNumberSetRequestTrackingNumber.validateJsonObject(item);
            };
        }

        return true;
    }


}



/**
 * Массив с парами идентификатор отправления — трек-номер.
 * @member {Array.<module:model/FbsPostingTrackingNumberSetRequestTrackingNumber>} tracking_numbers
 */
PostingFbsPostingTrackingNumberSetRequest.prototype['tracking_numbers'] = undefined;






export default PostingFbsPostingTrackingNumberSetRequest;

