/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DeleteProductsRequestProduct from './DeleteProductsRequestProduct';

/**
 * The Productv2DeleteProductsRequest model module.
 * @module model/Productv2DeleteProductsRequest
 * @version 2.1
 */
class Productv2DeleteProductsRequest {
    /**
     * Constructs a new <code>Productv2DeleteProductsRequest</code>.
     * @alias module:model/Productv2DeleteProductsRequest
     */
    constructor() { 
        
        Productv2DeleteProductsRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Productv2DeleteProductsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Productv2DeleteProductsRequest} obj Optional instance to populate.
     * @return {module:model/Productv2DeleteProductsRequest} The populated <code>Productv2DeleteProductsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Productv2DeleteProductsRequest();

            if (data.hasOwnProperty('products')) {
                obj['products'] = ApiClient.convertToType(data['products'], [DeleteProductsRequestProduct]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Productv2DeleteProductsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Productv2DeleteProductsRequest</code>.
     */
    static validateJSON(data) {
        if (data['products']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['products'])) {
                throw new Error("Expected the field `products` to be an array in the JSON data but got " + data['products']);
            }
            // validate the optional field `products` (array)
            for (const item of data['products']) {
                DeleteProductsRequestProduct.validateJsonObject(item);
            };
        }

        return true;
    }


}



/**
 * Идентификатор товара.
 * @member {Array.<module:model/DeleteProductsRequestProduct>} products
 */
Productv2DeleteProductsRequest.prototype['products'] = undefined;






export default Productv2DeleteProductsRequest;

