/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReportCreateCompanyFinanceReportRequest model module.
 * @module model/ReportCreateCompanyFinanceReportRequest
 * @version 2.1
 */
class ReportCreateCompanyFinanceReportRequest {
    /**
     * Constructs a new <code>ReportCreateCompanyFinanceReportRequest</code>.
     * @alias module:model/ReportCreateCompanyFinanceReportRequest
     */
    constructor() { 
        
        ReportCreateCompanyFinanceReportRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReportCreateCompanyFinanceReportRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReportCreateCompanyFinanceReportRequest} obj Optional instance to populate.
     * @return {module:model/ReportCreateCompanyFinanceReportRequest} The populated <code>ReportCreateCompanyFinanceReportRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReportCreateCompanyFinanceReportRequest();

            if (data.hasOwnProperty('date_from')) {
                obj['date_from'] = ApiClient.convertToType(data['date_from'], 'String');
            }
            if (data.hasOwnProperty('date_to')) {
                obj['date_to'] = ApiClient.convertToType(data['date_to'], 'String');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = ApiClient.convertToType(data['language'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReportCreateCompanyFinanceReportRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReportCreateCompanyFinanceReportRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['date_from'] && !(typeof data['date_from'] === 'string' || data['date_from'] instanceof String)) {
            throw new Error("Expected the field `date_from` to be a primitive type in the JSON string but got " + data['date_from']);
        }
        // ensure the json data is a string
        if (data['date_to'] && !(typeof data['date_to'] === 'string' || data['date_to'] instanceof String)) {
            throw new Error("Expected the field `date_to` to be a primitive type in the JSON string but got " + data['date_to']);
        }
        // ensure the json data is a string
        if (data['language'] && !(typeof data['language'] === 'string' || data['language'] instanceof String)) {
            throw new Error("Expected the field `language` to be a primitive type in the JSON string but got " + data['language']);
        }

        return true;
    }


}



/**
 * Дата, с ĸоторой рассчитывается отчёт по финансам. Формат: YYYY-MM-DD. 
 * @member {String} date_from
 */
ReportCreateCompanyFinanceReportRequest.prototype['date_from'] = undefined;

/**
 * Дата, по ĸоторую рассчитывается отчёт по финансам. Формат: YYYY-MM-DD. 
 * @member {String} date_to
 */
ReportCreateCompanyFinanceReportRequest.prototype['date_to'] = undefined;

/**
 * Язык ответа:   - `RU` — русский,   - `EN` — английский. 
 * @member {String} language
 * @default 'DEFAULT'
 */
ReportCreateCompanyFinanceReportRequest.prototype['language'] = 'DEFAULT';






export default ReportCreateCompanyFinanceReportRequest;

