/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1AutoBookingsGetV1Request model module.
 * @module model/V1AutoBookingsGetV1Request
 * @version 2.1
 */
class V1AutoBookingsGetV1Request {
    /**
     * Constructs a new <code>V1AutoBookingsGetV1Request</code>.
     * @alias module:model/V1AutoBookingsGetV1Request
     * @param bookingId {Number} Идентификатор бронирования.
     */
    constructor(bookingId) { 
        
        V1AutoBookingsGetV1Request.initialize(this, bookingId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, bookingId) { 
        obj['booking_id'] = bookingId;
    }

    /**
     * Constructs a <code>V1AutoBookingsGetV1Request</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1AutoBookingsGetV1Request} obj Optional instance to populate.
     * @return {module:model/V1AutoBookingsGetV1Request} The populated <code>V1AutoBookingsGetV1Request</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1AutoBookingsGetV1Request();

            if (data.hasOwnProperty('booking_id')) {
                obj['booking_id'] = ApiClient.convertToType(data['booking_id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1AutoBookingsGetV1Request</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1AutoBookingsGetV1Request</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1AutoBookingsGetV1Request.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

V1AutoBookingsGetV1Request.RequiredProperties = ["booking_id"];

/**
 * Идентификатор бронирования.
 * @member {Number} booking_id
 */
V1AutoBookingsGetV1Request.prototype['booking_id'] = undefined;






export default V1AutoBookingsGetV1Request;

