/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AutoModificationsListV1ResponseModification from './AutoModificationsListV1ResponseModification';

/**
 * The V1AutoModificationsListV1Response model module.
 * @module model/V1AutoModificationsListV1Response
 * @version 2.1
 */
class V1AutoModificationsListV1Response {
    /**
     * Constructs a new <code>V1AutoModificationsListV1Response</code>.
     * @alias module:model/V1AutoModificationsListV1Response
     */
    constructor() { 
        
        V1AutoModificationsListV1Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1AutoModificationsListV1Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1AutoModificationsListV1Response} obj Optional instance to populate.
     * @return {module:model/V1AutoModificationsListV1Response} The populated <code>V1AutoModificationsListV1Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1AutoModificationsListV1Response();

            if (data.hasOwnProperty('modifications')) {
                obj['modifications'] = AutoModificationsListV1ResponseModification.constructFromObject(data['modifications']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1AutoModificationsListV1Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1AutoModificationsListV1Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `modifications`
        if (data['modifications']) { // data not null
          AutoModificationsListV1ResponseModification.validateJSON(data['modifications']);
        }

        return true;
    }


}



/**
 * @member {module:model/AutoModificationsListV1ResponseModification} modifications
 */
V1AutoModificationsListV1Response.prototype['modifications'] = undefined;






export default V1AutoModificationsListV1Response;

