/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1GetProductInfoDiscountedRequest model module.
 * @module model/V1GetProductInfoDiscountedRequest
 * @version 2.1
 */
class V1GetProductInfoDiscountedRequest {
    /**
     * Constructs a new <code>V1GetProductInfoDiscountedRequest</code>.
     * @alias module:model/V1GetProductInfoDiscountedRequest
     */
    constructor() { 
        
        V1GetProductInfoDiscountedRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1GetProductInfoDiscountedRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1GetProductInfoDiscountedRequest} obj Optional instance to populate.
     * @return {module:model/V1GetProductInfoDiscountedRequest} The populated <code>V1GetProductInfoDiscountedRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1GetProductInfoDiscountedRequest();

            if (data.hasOwnProperty('discounted_skus')) {
                obj['discounted_skus'] = ApiClient.convertToType(data['discounted_skus'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1GetProductInfoDiscountedRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1GetProductInfoDiscountedRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['discounted_skus'])) {
            throw new Error("Expected the field `discounted_skus` to be an array in the JSON data but got " + data['discounted_skus']);
        }

        return true;
    }


}



/**
 * Список SKU уценённых товаров.
 * @member {Array.<String>} discounted_skus
 */
V1GetProductInfoDiscountedRequest.prototype['discounted_skus'] = undefined;






export default V1GetProductInfoDiscountedRequest;

