/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1ProductUploadDigitalCodesResponseResult model module.
 * @module model/V1ProductUploadDigitalCodesResponseResult
 * @version 2.1
 */
class V1ProductUploadDigitalCodesResponseResult {
    /**
     * Constructs a new <code>V1ProductUploadDigitalCodesResponseResult</code>.
     * @alias module:model/V1ProductUploadDigitalCodesResponseResult
     */
    constructor() { 
        
        V1ProductUploadDigitalCodesResponseResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1ProductUploadDigitalCodesResponseResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1ProductUploadDigitalCodesResponseResult} obj Optional instance to populate.
     * @return {module:model/V1ProductUploadDigitalCodesResponseResult} The populated <code>V1ProductUploadDigitalCodesResponseResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1ProductUploadDigitalCodesResponseResult();

            if (data.hasOwnProperty('task_id')) {
                obj['task_id'] = ApiClient.convertToType(data['task_id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1ProductUploadDigitalCodesResponseResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1ProductUploadDigitalCodesResponseResult</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Код задачи на загрузку кодов.
 * @member {Number} task_id
 */
V1ProductUploadDigitalCodesResponseResult.prototype['task_id'] = undefined;






export default V1ProductUploadDigitalCodesResponseResult;

