/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V3Cancellation model module.
 * @module model/V3Cancellation
 * @version 2.1
 */
class V3Cancellation {
    /**
     * Constructs a new <code>V3Cancellation</code>.
     * Информация об отмене.
     * @alias module:model/V3Cancellation
     */
    constructor() { 
        
        V3Cancellation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V3Cancellation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V3Cancellation} obj Optional instance to populate.
     * @return {module:model/V3Cancellation} The populated <code>V3Cancellation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V3Cancellation();

            if (data.hasOwnProperty('affect_cancellation_rating')) {
                obj['affect_cancellation_rating'] = ApiClient.convertToType(data['affect_cancellation_rating'], 'Boolean');
            }
            if (data.hasOwnProperty('cancel_reason')) {
                obj['cancel_reason'] = ApiClient.convertToType(data['cancel_reason'], 'String');
            }
            if (data.hasOwnProperty('cancel_reason_id')) {
                obj['cancel_reason_id'] = ApiClient.convertToType(data['cancel_reason_id'], 'Number');
            }
            if (data.hasOwnProperty('cancellation_initiator')) {
                obj['cancellation_initiator'] = ApiClient.convertToType(data['cancellation_initiator'], 'String');
            }
            if (data.hasOwnProperty('cancellation_type')) {
                obj['cancellation_type'] = ApiClient.convertToType(data['cancellation_type'], 'String');
            }
            if (data.hasOwnProperty('cancelled_after_ship')) {
                obj['cancelled_after_ship'] = ApiClient.convertToType(data['cancelled_after_ship'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V3Cancellation</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V3Cancellation</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['cancel_reason'] && !(typeof data['cancel_reason'] === 'string' || data['cancel_reason'] instanceof String)) {
            throw new Error("Expected the field `cancel_reason` to be a primitive type in the JSON string but got " + data['cancel_reason']);
        }
        // ensure the json data is a string
        if (data['cancellation_initiator'] && !(typeof data['cancellation_initiator'] === 'string' || data['cancellation_initiator'] instanceof String)) {
            throw new Error("Expected the field `cancellation_initiator` to be a primitive type in the JSON string but got " + data['cancellation_initiator']);
        }
        // ensure the json data is a string
        if (data['cancellation_type'] && !(typeof data['cancellation_type'] === 'string' || data['cancellation_type'] instanceof String)) {
            throw new Error("Expected the field `cancellation_type` to be a primitive type in the JSON string but got " + data['cancellation_type']);
        }

        return true;
    }


}



/**
 * Если отмена влияет на рейтинг продавца — `true`.
 * @member {Boolean} affect_cancellation_rating
 */
V3Cancellation.prototype['affect_cancellation_rating'] = undefined;

/**
 * Причина отмены.
 * @member {String} cancel_reason
 */
V3Cancellation.prototype['cancel_reason'] = undefined;

/**
 * Идентификатор причины отмены отправления.
 * @member {Number} cancel_reason_id
 */
V3Cancellation.prototype['cancel_reason_id'] = undefined;

/**
 * Инициатор отмены отправления: - `Клиент`, - `Ozon`, - `Продавец`. 
 * @member {String} cancellation_initiator
 */
V3Cancellation.prototype['cancellation_initiator'] = undefined;

/**
 * Тип отмены отправления: - `client` — клиентская. - `ozon` — отменено Ozon. - `seller` — отменено продавцом. 
 * @member {String} cancellation_type
 */
V3Cancellation.prototype['cancellation_type'] = undefined;

/**
 * Если отмена произошла после сборки отправления — `true`.
 * @member {Boolean} cancelled_after_ship
 */
V3Cancellation.prototype['cancelled_after_ship'] = undefined;






export default V3Cancellation;

