/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetProductRatingBySkuResponseRatingCondition model module.
 * @module model/GetProductRatingBySkuResponseRatingCondition
 * @version 2.1
 */
class GetProductRatingBySkuResponseRatingCondition {
    /**
     * Constructs a new <code>GetProductRatingBySkuResponseRatingCondition</code>.
     * @alias module:model/GetProductRatingBySkuResponseRatingCondition
     */
    constructor() { 
        
        GetProductRatingBySkuResponseRatingCondition.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetProductRatingBySkuResponseRatingCondition</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetProductRatingBySkuResponseRatingCondition} obj Optional instance to populate.
     * @return {module:model/GetProductRatingBySkuResponseRatingCondition} The populated <code>GetProductRatingBySkuResponseRatingCondition</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetProductRatingBySkuResponseRatingCondition();

            if (data.hasOwnProperty('cost')) {
                obj['cost'] = ApiClient.convertToType(data['cost'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('fulfilled')) {
                obj['fulfilled'] = ApiClient.convertToType(data['fulfilled'], 'Boolean');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetProductRatingBySkuResponseRatingCondition</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetProductRatingBySkuResponseRatingCondition</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['key'] && !(typeof data['key'] === 'string' || data['key'] instanceof String)) {
            throw new Error("Expected the field `key` to be a primitive type in the JSON string but got " + data['key']);
        }

        return true;
    }


}



/**
 * Количество баллов контент-рейтинга, которое даёт выполнение условия.
 * @member {Number} cost
 */
GetProductRatingBySkuResponseRatingCondition.prototype['cost'] = undefined;

/**
 * Описание условия.
 * @member {String} description
 */
GetProductRatingBySkuResponseRatingCondition.prototype['description'] = undefined;

/**
 * Признак, что условие выполнено.
 * @member {Boolean} fulfilled
 */
GetProductRatingBySkuResponseRatingCondition.prototype['fulfilled'] = undefined;

/**
 * Идентификатор условия.
 * @member {String} key
 */
GetProductRatingBySkuResponseRatingCondition.prototype['key'] = undefined;






export default GetProductRatingBySkuResponseRatingCondition;

