/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetProductInfoLimitResponseDailyQuota model module.
 * @module model/GetProductInfoLimitResponseDailyQuota
 * @version 2.1
 */
class GetProductInfoLimitResponseDailyQuota {
    /**
     * Constructs a new <code>GetProductInfoLimitResponseDailyQuota</code>.
     * Суточные лимиты.
     * @alias module:model/GetProductInfoLimitResponseDailyQuota
     */
    constructor() { 
        
        GetProductInfoLimitResponseDailyQuota.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetProductInfoLimitResponseDailyQuota</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetProductInfoLimitResponseDailyQuota} obj Optional instance to populate.
     * @return {module:model/GetProductInfoLimitResponseDailyQuota} The populated <code>GetProductInfoLimitResponseDailyQuota</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetProductInfoLimitResponseDailyQuota();

            if (data.hasOwnProperty('all_quota_value')) {
                obj['all_quota_value'] = ApiClient.convertToType(data['all_quota_value'], 'Number');
            }
            if (data.hasOwnProperty('all_remaining_value')) {
                obj['all_remaining_value'] = ApiClient.convertToType(data['all_remaining_value'], 'Number');
            }
            if (data.hasOwnProperty('create_quota_value')) {
                obj['create_quota_value'] = ApiClient.convertToType(data['create_quota_value'], 'Number');
            }
            if (data.hasOwnProperty('create_remaining_value')) {
                obj['create_remaining_value'] = ApiClient.convertToType(data['create_remaining_value'], 'Number');
            }
            if (data.hasOwnProperty('reset_at')) {
                obj['reset_at'] = ApiClient.convertToType(data['reset_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetProductInfoLimitResponseDailyQuota</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetProductInfoLimitResponseDailyQuota</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Общий суточный лимит на создание и обновление товаров.
 * @member {Number} all_quota_value
 */
GetProductInfoLimitResponseDailyQuota.prototype['all_quota_value'] = undefined;

/**
 * Сколько осталось от общего суточного лимита на создание и обновление товаров до конца суток.
 * @member {Number} all_remaining_value
 */
GetProductInfoLimitResponseDailyQuota.prototype['all_remaining_value'] = undefined;

/**
 * Суточный лимит на создание товаров.
 * @member {Number} create_quota_value
 */
GetProductInfoLimitResponseDailyQuota.prototype['create_quota_value'] = undefined;

/**
 * Сколько осталось от суточного лимита на создание товаров до конца суток.
 * @member {Number} create_remaining_value
 */
GetProductInfoLimitResponseDailyQuota.prototype['create_remaining_value'] = undefined;

/**
 * Время в формате UTC, когда сбросится значение счётчика за текущие сутки.
 * @member {Date} reset_at
 */
GetProductInfoLimitResponseDailyQuota.prototype['reset_at'] = undefined;






export default GetProductInfoLimitResponseDailyQuota;

