/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Productv4Filter from './Productv4Filter';

/**
 * The Productv4GetProductInfoPricesV4Request model module.
 * @module model/Productv4GetProductInfoPricesV4Request
 * @version 2.1
 */
class Productv4GetProductInfoPricesV4Request {
    /**
     * Constructs a new <code>Productv4GetProductInfoPricesV4Request</code>.
     * @alias module:model/Productv4GetProductInfoPricesV4Request
     */
    constructor() { 
        
        Productv4GetProductInfoPricesV4Request.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Productv4GetProductInfoPricesV4Request</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Productv4GetProductInfoPricesV4Request} obj Optional instance to populate.
     * @return {module:model/Productv4GetProductInfoPricesV4Request} The populated <code>Productv4GetProductInfoPricesV4Request</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Productv4GetProductInfoPricesV4Request();

            if (data.hasOwnProperty('filter')) {
                obj['filter'] = Productv4Filter.constructFromObject(data['filter']);
            }
            if (data.hasOwnProperty('last_id')) {
                obj['last_id'] = ApiClient.convertToType(data['last_id'], 'String');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Productv4GetProductInfoPricesV4Request</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Productv4GetProductInfoPricesV4Request</code>.
     */
    static validateJSON(data) {
        // validate the optional field `filter`
        if (data['filter']) { // data not null
          Productv4Filter.validateJSON(data['filter']);
        }
        // ensure the json data is a string
        if (data['last_id'] && !(typeof data['last_id'] === 'string' || data['last_id'] instanceof String)) {
            throw new Error("Expected the field `last_id` to be a primitive type in the JSON string but got " + data['last_id']);
        }

        return true;
    }


}



/**
 * @member {module:model/Productv4Filter} filter
 */
Productv4GetProductInfoPricesV4Request.prototype['filter'] = undefined;

/**
 * Идентификатор последнего значения на странице. Оставьте это поле пустым при выполнении первого запроса.  Чтобы получить следующие значения, укажите `last_id` из ответа предыдущего запроса. 
 * @member {String} last_id
 */
Productv4GetProductInfoPricesV4Request.prototype['last_id'] = undefined;

/**
 * Количество значений на странице. Минимум — 1, максимум — 1000.
 * @member {Number} limit
 */
Productv4GetProductInfoPricesV4Request.prototype['limit'] = undefined;






export default Productv4GetProductInfoPricesV4Request;

