/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductGetImportProductsInfoResponseResult from './ProductGetImportProductsInfoResponseResult';

/**
 * The ProductGetImportProductsInfoResponse model module.
 * @module model/ProductGetImportProductsInfoResponse
 * @version 2.1
 */
class ProductGetImportProductsInfoResponse {
    /**
     * Constructs a new <code>ProductGetImportProductsInfoResponse</code>.
     * @alias module:model/ProductGetImportProductsInfoResponse
     */
    constructor() { 
        
        ProductGetImportProductsInfoResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductGetImportProductsInfoResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductGetImportProductsInfoResponse} obj Optional instance to populate.
     * @return {module:model/ProductGetImportProductsInfoResponse} The populated <code>ProductGetImportProductsInfoResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductGetImportProductsInfoResponse();

            if (data.hasOwnProperty('result')) {
                obj['result'] = ProductGetImportProductsInfoResponseResult.constructFromObject(data['result']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductGetImportProductsInfoResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductGetImportProductsInfoResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `result`
        if (data['result']) { // data not null
          ProductGetImportProductsInfoResponseResult.validateJSON(data['result']);
        }

        return true;
    }


}



/**
 * @member {module:model/ProductGetImportProductsInfoResponseResult} result
 */
ProductGetImportProductsInfoResponse.prototype['result'] = undefined;






export default ProductGetImportProductsInfoResponse;

