/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SellerApiGetSellerProductV1ResponseResult from './SellerApiGetSellerProductV1ResponseResult';

/**
 * The SellerApiGetSellerProductV1Response model module.
 * @module model/SellerApiGetSellerProductV1Response
 * @version 2.1
 */
class SellerApiGetSellerProductV1Response {
    /**
     * Constructs a new <code>SellerApiGetSellerProductV1Response</code>.
     * @alias module:model/SellerApiGetSellerProductV1Response
     */
    constructor() { 
        
        SellerApiGetSellerProductV1Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SellerApiGetSellerProductV1Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SellerApiGetSellerProductV1Response} obj Optional instance to populate.
     * @return {module:model/SellerApiGetSellerProductV1Response} The populated <code>SellerApiGetSellerProductV1Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SellerApiGetSellerProductV1Response();

            if (data.hasOwnProperty('result')) {
                obj['result'] = SellerApiGetSellerProductV1ResponseResult.constructFromObject(data['result']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SellerApiGetSellerProductV1Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SellerApiGetSellerProductV1Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `result`
        if (data['result']) { // data not null
          SellerApiGetSellerProductV1ResponseResult.validateJSON(data['result']);
        }

        return true;
    }


}



/**
 * @member {module:model/SellerApiGetSellerProductV1ResponseResult} result
 */
SellerApiGetSellerProductV1Response.prototype['result'] = undefined;






export default SellerApiGetSellerProductV1Response;

