/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AutoOffersListV1RequestFilter from './AutoOffersListV1RequestFilter';

/**
 * The V1AutoOffersListV1Request model module.
 * @module model/V1AutoOffersListV1Request
 * @version 2.1
 */
class V1AutoOffersListV1Request {
    /**
     * Constructs a new <code>V1AutoOffersListV1Request</code>.
     * Фильтр.
     * @alias module:model/V1AutoOffersListV1Request
     * @param lastId {String} Идентификатор последнего значения на странице. Оставьте это поле пустым при выполнении первого запроса.  Чтобы получить следующие значения, укажите `last_id` из ответа предыдущего запроса. 
     * @param limit {Number} Количество предложений на странице. Минимальное значение — 1, максимальное — 1000.
     */
    constructor(lastId, limit) { 
        
        V1AutoOffersListV1Request.initialize(this, lastId, limit);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, lastId, limit) { 
        obj['last_id'] = lastId;
        obj['limit'] = limit;
    }

    /**
     * Constructs a <code>V1AutoOffersListV1Request</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1AutoOffersListV1Request} obj Optional instance to populate.
     * @return {module:model/V1AutoOffersListV1Request} The populated <code>V1AutoOffersListV1Request</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1AutoOffersListV1Request();

            if (data.hasOwnProperty('filter')) {
                obj['filter'] = AutoOffersListV1RequestFilter.constructFromObject(data['filter']);
            }
            if (data.hasOwnProperty('last_id')) {
                obj['last_id'] = ApiClient.convertToType(data['last_id'], 'String');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1AutoOffersListV1Request</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1AutoOffersListV1Request</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of V1AutoOffersListV1Request.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `filter`
        if (data['filter']) { // data not null
          AutoOffersListV1RequestFilter.validateJSON(data['filter']);
        }
        // ensure the json data is a string
        if (data['last_id'] && !(typeof data['last_id'] === 'string' || data['last_id'] instanceof String)) {
            throw new Error("Expected the field `last_id` to be a primitive type in the JSON string but got " + data['last_id']);
        }

        return true;
    }


}

V1AutoOffersListV1Request.RequiredProperties = ["last_id", "limit"];

/**
 * @member {module:model/AutoOffersListV1RequestFilter} filter
 */
V1AutoOffersListV1Request.prototype['filter'] = undefined;

/**
 * Идентификатор последнего значения на странице. Оставьте это поле пустым при выполнении первого запроса.  Чтобы получить следующие значения, укажите `last_id` из ответа предыдущего запроса. 
 * @member {String} last_id
 */
V1AutoOffersListV1Request.prototype['last_id'] = undefined;

/**
 * Количество предложений на странице. Минимальное значение — 1, максимальное — 1000.
 * @member {Number} limit
 */
V1AutoOffersListV1Request.prototype['limit'] = undefined;






export default V1AutoOffersListV1Request;

