/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1DeclineDiscountTasksRequestTask model module.
 * @module model/V1DeclineDiscountTasksRequestTask
 * @version 2.1
 */
class V1DeclineDiscountTasksRequestTask {
    /**
     * Constructs a new <code>V1DeclineDiscountTasksRequestTask</code>.
     * @alias module:model/V1DeclineDiscountTasksRequestTask
     */
    constructor() { 
        
        V1DeclineDiscountTasksRequestTask.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1DeclineDiscountTasksRequestTask</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1DeclineDiscountTasksRequestTask} obj Optional instance to populate.
     * @return {module:model/V1DeclineDiscountTasksRequestTask} The populated <code>V1DeclineDiscountTasksRequestTask</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1DeclineDiscountTasksRequestTask();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('seller_comment')) {
                obj['seller_comment'] = ApiClient.convertToType(data['seller_comment'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1DeclineDiscountTasksRequestTask</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1DeclineDiscountTasksRequestTask</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['seller_comment'] && !(typeof data['seller_comment'] === 'string' || data['seller_comment'] instanceof String)) {
            throw new Error("Expected the field `seller_comment` to be a primitive type in the JSON string but got " + data['seller_comment']);
        }

        return true;
    }


}



/**
 * Идентификатор заявки.
 * @member {Number} id
 */
V1DeclineDiscountTasksRequestTask.prototype['id'] = undefined;

/**
 * Комментарий продавца к заявке.
 * @member {String} seller_comment
 */
V1DeclineDiscountTasksRequestTask.prototype['seller_comment'] = undefined;






export default V1DeclineDiscountTasksRequestTask;

