/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1GetHotSalesProductsRequest model module.
 * @module model/V1GetHotSalesProductsRequest
 * @version 2.1
 */
class V1GetHotSalesProductsRequest {
    /**
     * Constructs a new <code>V1GetHotSalesProductsRequest</code>.
     * @alias module:model/V1GetHotSalesProductsRequest
     */
    constructor() { 
        
        V1GetHotSalesProductsRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1GetHotSalesProductsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1GetHotSalesProductsRequest} obj Optional instance to populate.
     * @return {module:model/V1GetHotSalesProductsRequest} The populated <code>V1GetHotSalesProductsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1GetHotSalesProductsRequest();

            if (data.hasOwnProperty('hotsale_id')) {
                obj['hotsale_id'] = ApiClient.convertToType(data['hotsale_id'], 'Number');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1GetHotSalesProductsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1GetHotSalesProductsRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Идентификатор акции Hot Sale.
 * @member {Number} hotsale_id
 */
V1GetHotSalesProductsRequest.prototype['hotsale_id'] = undefined;

/**
 * Количество элементов в ответе. По умолчанию — 100.
 * @member {Number} limit
 */
V1GetHotSalesProductsRequest.prototype['limit'] = undefined;

/**
 * Количество элементов, которое будет пропущено в ответе. Например, если `offset = 10`, то ответ начнётся с 11-го найденного элемента.
 * @member {Number} offset
 */
V1GetHotSalesProductsRequest.prototype['offset'] = undefined;






export default V1GetHotSalesProductsRequest;

