/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V2ChatReadResponse model module.
 * @module model/V2ChatReadResponse
 * @version 2.1
 */
class V2ChatReadResponse {
    /**
     * Constructs a new <code>V2ChatReadResponse</code>.
     * @alias module:model/V2ChatReadResponse
     */
    constructor() { 
        
        V2ChatReadResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V2ChatReadResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V2ChatReadResponse} obj Optional instance to populate.
     * @return {module:model/V2ChatReadResponse} The populated <code>V2ChatReadResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V2ChatReadResponse();

            if (data.hasOwnProperty('unread_count')) {
                obj['unread_count'] = ApiClient.convertToType(data['unread_count'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V2ChatReadResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V2ChatReadResponse</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Количество непрочитанных сообщений в чате.
 * @member {Number} unread_count
 */
V2ChatReadResponse.prototype['unread_count'] = undefined;






export default V2ChatReadResponse;

