/**
 * Документация Ozon Seller API
 * По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru) 
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V2PostingFBSActGetProducts from './V2PostingFBSActGetProducts';

/**
 * The V2PostingFBSActGetPostingsResult model module.
 * @module model/V2PostingFBSActGetPostingsResult
 * @version 2.1
 */
class V2PostingFBSActGetPostingsResult {
    /**
     * Constructs a new <code>V2PostingFBSActGetPostingsResult</code>.
     * @alias module:model/V2PostingFBSActGetPostingsResult
     */
    constructor() { 
        
        V2PostingFBSActGetPostingsResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V2PostingFBSActGetPostingsResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V2PostingFBSActGetPostingsResult} obj Optional instance to populate.
     * @return {module:model/V2PostingFBSActGetPostingsResult} The populated <code>V2PostingFBSActGetPostingsResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V2PostingFBSActGetPostingsResult();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('posting_number')) {
                obj['posting_number'] = ApiClient.convertToType(data['posting_number'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('seller_error')) {
                obj['seller_error'] = ApiClient.convertToType(data['seller_error'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = ApiClient.convertToType(data['products'], [V2PostingFBSActGetProducts]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V2PostingFBSActGetPostingsResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V2PostingFBSActGetPostingsResult</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['posting_number'] && !(typeof data['posting_number'] === 'string' || data['posting_number'] instanceof String)) {
            throw new Error("Expected the field `posting_number` to be a primitive type in the JSON string but got " + data['posting_number']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['seller_error'] && !(typeof data['seller_error'] === 'string' || data['seller_error'] instanceof String)) {
            throw new Error("Expected the field `seller_error` to be a primitive type in the JSON string but got " + data['seller_error']);
        }
        if (data['products']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['products'])) {
                throw new Error("Expected the field `products` to be an array in the JSON data but got " + data['products']);
            }
            // validate the optional field `products` (array)
            for (const item of data['products']) {
                V2PostingFBSActGetProducts.validateJsonObject(item);
            };
        }

        return true;
    }


}



/**
 * Идентификатор акта.
 * @member {Number} id
 */
V2PostingFBSActGetPostingsResult.prototype['id'] = undefined;

/**
 * Номер отправления.
 * @member {String} posting_number
 */
V2PostingFBSActGetPostingsResult.prototype['posting_number'] = undefined;

/**
 * Статус отправления.
 * @member {String} status
 */
V2PostingFBSActGetPostingsResult.prototype['status'] = undefined;

/**
 * Расшифровка кода ошибки.
 * @member {String} seller_error
 */
V2PostingFBSActGetPostingsResult.prototype['seller_error'] = undefined;

/**
 * Дата и время обновления записи об отправлении.
 * @member {Date} updated_at
 */
V2PostingFBSActGetPostingsResult.prototype['updated_at'] = undefined;

/**
 * Дата и время создания записи об отправлении.
 * @member {Date} created_at
 */
V2PostingFBSActGetPostingsResult.prototype['created_at'] = undefined;

/**
 * Список товаров в отправлении.
 * @member {Array.<module:model/V2PostingFBSActGetProducts>} products
 */
V2PostingFBSActGetPostingsResult.prototype['products'] = undefined;






export default V2PostingFBSActGetPostingsResult;

